version: '3.2'

services:
  main-build:
    build: .
    image: docker/libgemini:1.0
    volumes:
      - type: bind
        source: ./
        target: /tmp
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.56.0/24