version: '1.0'

services:
  main-build:
    build: .
    image: libgemini:1.0
    volumes:
      - type: bind
        source: ./
        target: /tmp
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24